#!/bin/bash

declare -a arr=("facebook.txt", "s420_txt.txt", "yeastInter.txt", "hiv.txt", "netsci.txt", "gene_fusion.txt", "hiv.txt", "netsci.txt", "similarities.txt", "euroroad.txt", "icefiresocial.txt", "metabolite.txt", "hamster.txt", "sistercities.txt")

for i in in "${arr[@]}"
do
	./clawfinder "$i false"
done